
export const propertydata =[
    {
        id: 1,
        date:"1 Jan 2021",
        purpose: "FOR SALE",
        img: "https://raw.githubusercontent.com/OloriAsabi/book-images/main/src/rent/Asokoro-Abuja..jpg",
        title: "5 Bedroom Apartment",
        address: "Lagos",
        bedroom: "1",
        bathroom: "2",
        toilet: "1",
        amount: "50000",
    },
    {
        id:2,
        date:"1 Jan 2021",
        purpose: "FOR RENT",
        img: "https://raw.githubusercontent.com/OloriAsabi/book-images/main/src/rent/021-casa-pi-taller-aragons.jpg",
        title: "5 Bedroom Apartment",
        address: "Lagos",
        bedroom: "2",
        bathroom: "3",
        toilet: "4",
        amount: "1250000",

    },
    {
        id:3,
        date:"1 Jan 2021",
        purpose: "FOR SALE",
        img: "https://raw.githubusercontent.com/OloriAsabi/book-images/main/src/rent/05e87b13093bb1-luxury-detached-duplex-with-2-room-bq-white-house-at-ajah-n180m-detached-duplexes-for-sale-lekki-expressway-lekki-lagos.jpg",
        title: "5 Bedroom Apartment",
        address: "Abuja",
        bedroom: "1",
        bathroom: "2",
        toilet: "2",
        amount: "350000",
    },
    {
        id:4,
        date:"1 Jan 2021",
        purpose: "FOR SALE",
        img: "https://raw.githubusercontent.com/OloriAsabi/book-images/main/src/rent/4-bedroom-bungalow-hp1-1-1024x652.webp",
        title: "5 Bedroom Apartment",
        address: "Ajah",
        bedroom: "4",
        bathroom: "5",
        toilet: "5",
        amount: "450000",
    },
    {
        id:5,
        date:"1 Jan 2021",
        purpose: "FOR RENT",
        img: "https://raw.githubusercontent.com/OloriAsabi/book-images/main/src/rent/CA_AG_DUL_BGA_243.jpg",
        title: "5 Bedroom Apartment",
        address: "Lekki",
        bedroom: "3",
        bathroom: "4",
        toilet: "4",
        amount: "550000",
    },

]